export enum NotificationType {
  BID_OUTBID = "BID_OUTBID",
  AUCTION_WIN = "AUCTION_WIN",
  LISTING_APPROVED = "LISTING_APPROVED",
  CHAT_MESSAGE = "CHAT_MESSAGE",
  SELLER_REQUEST_REJECT = "YOUR_SELLER_REQUEST_HAS_BEEN_REJECTED",
  SELLER_REQUEST_APPROVAL = "YOUR_SELLER_REQUEST_HAS_BEEN_APPROVED",
  AUCTION_RESERVE_NOT_MET = "AUCTION_ENDED_BUT_RESERVE_PRICE_NOT_MET"
}